port: &port 3000

container:
  image: travel-list
  port: *port
  resourceTier: S

configMap:
  environment: production

secret:
  secretsPath: /travel-list

deployment: {}

ingress:
  host: travel-list.lynxmagnus.com

readinessProbe:
  httpGet:
    path: /healthz
    port: *port

livenessProbe:
  httpGet:
    path: /healthz
    port: *port

startupProbe:
  httpGet:
    path: /healthz
    port: *port
  initialDelaySeconds: 10
