services:
  travel-list:
    extends:
      file: docker-compose.test.yaml
      service: travel-list
    command: npm run test:watch
    volumes:
      - ./.git:/home/node/.git
      - ./src:/home/node/src
