services:
  travel-list:
    extends:
      file: docker-compose.yaml
      service: travel-list
    build:
      target: development
    image: travel-list-test
    container_name: travel-list-test
    command: npm run test
    volumes:
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
