services:
  travel-list:
    build:
      target: development
    image: travel-list-development
    container_name: travel-list-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json
    networks:
      - travel-list

networks:
  travel-list:
    driver: bridge
    name: travel-list
